name: cd

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install dependencies
        run: go mod download
      - name: Run build
        run: >-
          go build
          -o ssh-provision
          -ldflags "-X main.Name=ssh-provision -X main.Version=${GITHUB_REF:10}"
          cmd/ssh-provision/ssh-provision.go
        env:
          GOOS: linux
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ssh-provision
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
